### ISSUE TITLE
GitHub Actionsの設定

### ISSUE THREAD

**Issue by yitsturdy** [yitstudy/SOSOMETRON#21]
https://github.com/wakiy1031/template_Next.js-15_Rails-8

```my-app/
├── .github/
│   └── workflows/          # GitHub Actions設定
│       ├── frontend.yml    # フロントエンド用CI/CD
│       └── backend.yml     # バックエンド用CI/CD
├── frontend/               # Next.jsアプリケーション
└── backend/               # Rails APIアプリケーション
```

[バックエンドデプロイ用のGitHub Actions作成](https://zenn.dev/meimei_kr/articles/8138865b92e99d#%E3%83%90%E3%83%83%E3%82%AF%E3%82%A8%E3%83%B3%E3%83%89%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4%E7%94%A8%E3%81%AEgithub-actions%E4%BD%9C%E6%88%90)

**Comment by yitsturdy** [comment]
```
name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install dependencies
        run: |
          cd frontend && npm install
          cd ../backend && bundle install
      - name: Run tests
        run: |
          cd frontend && npm test
          cd ../backend && rails test
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push frontend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: portfolio-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd frontend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Build, tag, and push backend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: portfolio-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: portfolio-service
          cluster: portfolio-cluster
          wait-for-service-stability: true
```
