### ISSUE TITLE
AWSでデプロイ

### ISSUE THREAD

**Issue by yitsturdy** [yitstudy/SOSOMETRON#27]
AWSへのデプロイ

## AWSリソースのセットアップ
- S3: Next.jsの静的アセット（_next/staticなど）をホスト
  - バケットを作成し、静的ウェブホスティングを有効化
- RDS: PostgreSQLデータベースセキュリティグループでECSからのアクセスを許可
- ECS Fargate:クラスタを作成タスク定義でNext.jsとRailsのコンテナを定義ALB（Application Load Balancer）を設定し、HTTPSを有効化
- Route 53: ドメインをALBにマッピング
- ACM: SSL証明書を発行
## 環境変数の設定
- ECSタスク定義で以下を指定
```yaml
environment:
  - name: NEXT_PUBLIC_API_URL
    value: https://api.yourdomain.com
  - name: DATABASE_URL value:postgres://user:password@rds-endpoint:5432/portfolio_production
```
## Dockerイメージのビルドとプッシュ
- ECR（Elastic Container Registry）にリポジトリを作成
- Dockerイメージをビルドし、ECRにプッシュ
```bash
aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <account-id>.dkr.ecr.us-east-1.amazonaws.com
docker build -t portfolio-frontend ./frontend
docker tag portfolio-frontend:latest <account-id>.dkr.ecr.us-east-1.amazonaws.com/portfolio-frontend:latest
docker push <account-id>.dkr.ecr.us-east-1.amazonaws.com/portfolio-frontend:latest
```
